import React from "react";
import { registerLicense } from '@syncfusion/ej2-base';
import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/server/sidebar";

const license = process.env.SYNCFUSION_LICENSE ?? '';

if (license) {
    registerLicense(license);
} else {
    if (process.env.NODE_ENV === 'development') {
        console.warn('SYNCFUSION_LICENSE not set');
    }
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
            <Sidebar />

            <main className="bg-gray-50 flex-1 p-6 min-h-screen">
                {children}
            </main>

        </div>
      </body>
    </html>
  );
}
